#!/bin/bash

#Place podfile with project name where it needs to be (assuming git clone executed from project root)
PROJECT_NAME=$(awk -F"[ '.]+" '$1 == "project"{print $2}' ../ios/Podfile)
echo "Writing Podfile for project $PROJECT_NAME \n"
sed -i '' "s/forcetest/$PROJECT_NAME/g" Podfile
mv Podfile ../ios/Podfile

#npm dependencies (DO NOT USE REACT-NATIVE LINK)
npm i events react-native-calendar-picker react-native-swiper https://github.com/ForceDotComLabs/react.force.git redux react-redux redux-logger redux-thunk react-native-fetch-blob react-native-geocoder https://github.com/mkoo21/react-native-mail https://github.com/aluksidadi/react-native-quick-look.git react-native-side-menu react-native-sortable-listview react-native-star-rating react-native-video https://github.com/ForceDotComLabs/react.force.base.theme.git#master https://github.com/ForceDotComLabs/react.force.data.git https://github.com/ForceDotComLabs/react.force.datacontainer.git https://github.com/forceDotComLabs/react.force.layout.git
react-native link redux events react-native-calendar-picker react-native-swiper react-redux redux-logger redux-thunk react-native-fetch-blob react-native-geocoder react-native-mail react-native-quick-look react-native-side-menu react-native-sortable-listview react-native-star-rating react-native-video react.force.base.theme react.force.data react.force.datacontainer react.force.layout


#npm dependencies that support cocoapods (you need to also add them to podfile)
npm i react-native-vector-icons
npm i react-native-code-push
npm i react-native-maps
npm i https://github.com/mkoo21/react-native-fs

#Cocoapods
cd ../ios && pod install

#Cleanup
rm -rf ../salesforcesdk5-ios-install